### ISSUE TITLE
Build failure with base-4.18 (GHC 9.6)

### ISSUE THREAD

**Issue by andreasabel** [simonmichael/shelltestrunner#33]
Due to the addition of `traceWith` in `base-4.18`, the package fails to build with GHC 9.6:
```haskell 
[2 of 7] Compiling Utils.Debug      ( src/Utils/Debug.hs, ... )

src/Utils/Debug.hs:60:10: error:
    Ambiguous occurrence ‘traceWith’
    It could refer to
       either ‘Debug.Trace.traceWith’,
              imported from ‘Debug.Trace’ at src/Utils/Debug.hs:33:1-18
           or ‘Utils.Debug.traceWith’, defined at src/Utils/Debug.hs:56:1
   |
60 | strace = traceWith show
   |          ^^^^^^^^^
```
I made revisions on Hackage to restrict `base` to `<4.18` for the newest versions of `shelltestrunner`.

Suggestion:  Make all imports explicit to be more resilient against upstream changes.  (The Haskell PVP allows API extensions even for minor version releases.  So clashes like these would  theoretically even be possible with a minor GHC release. However, I believe GHC abstains from API extensions in minor releases of `base`.))
