### PR TITLE
ghc 9.6

### LINKED ISSUE #33: Build failure with base-4.18 (GHC 9.6)
Due to the addition of `traceWith` in `base-4.18`, the package fails to build with GHC 9.6:
```haskell 
[2 of 7] Compiling Utils.Debug      ( src/Utils/Debug.hs, ... )

src/Utils/Debug.hs:60:10: error:
    Ambiguous occurrence ‘traceWith’
    It could refer to
       either ‘Debug.Trace.traceWith’,
              imported from ‘Debug.Trace’ at src/Utils/Debug.hs:33:1-18
           or ‘Utils.Debug.traceWith’, defined at src/Utils/Debug.hs:56:1
   |
60 | strace = traceWith show
   |          ^^^^^^^^^
```
I made revisions on Hackage to restrict `base` to `<4.18` for the newest versions of `shelltestrunner`.

Suggestion:  Make all imports explicit to be more resilient against upstream changes.  (The Haskell PVP allows API extensions even for minor version releases.  So clashes like these would  theoretically even be possible with a minor GHC release. However, I believe GHC abstains from API extensions in minor releases of `base`.))

### PR DESCRIPTION
**Pull request by andreasabel**
- Fix clash with base-4.18 which now exports `traceWith`
- Add GHC 9.6 to CI

Fixes #33.

Would be great to get a release so `shelltestrunner` can go into latest Stackage nightly again.
- https://github.com/commercialhaskell/stackage/issues/7036

### CODE REVIEW

**Comment by andreasabel** [comment]
PR is ready @simonmichael .
The test failure in https://github.com/andreasabel/shelltestrunner/actions/runs/5421337489/jobs/9856641808 seems due to stack printing a warning for GHC 9.6 and the test environment choking on it.

**Comment by simonmichael** [comment]
Thank you! I will update str soon.

**Comment by andreasabel** [comment]
I see that str has a lot of unreleased changes, which might block a swift release for GHC 9.6.
The only thing that stops working 1.9 with GHC 9.6 is the name clash for `debugWith`.

Would it make sense to publish a 1.9.0.1 which just fixes this problem?
In case, here is a sdist tarball: [shelltestrunner-1.9.0.1.tar.gz](https://github.com/simonmichael/shelltestrunner/files/12066778/shelltestrunner-1.9.0.1.tar.gz)

**Comment by andreasabel** [comment]
Ping @simonmichael

**Comment by simonmichael** [comment]
Hi @andreasabel - I'm sorry for the slow response. I haven't had mental space for this for a while. Would it be helpful to make you a maintainer on Hackage ?

**Comment by andreasabel** [comment]
Yes, @simonmichael, in this case I could upload the patch version 1.9.0.1.

**Comment by simonmichael** [comment]
I have done so, thank you !

**Comment by andreasabel** [comment]
Great, thanks!
- https://github.com/andreasabel/shelltestrunner/pull/1

Do you want to add me as collaborator on this repo as well so I can push the `release-1.9.0.1` branch (and then also a new tag) here?

**Comment by andreasabel** [comment]
@simonmichael : I release 1.9.0.1 to hackage: https://hackage.haskell.org/package/shelltestrunner-1.9.0.1

Here is the diff to 1.9: https://github.com/simonmichael/shelltestrunner/compare/1.9...andreasabel:shelltestrunner:release-1.9.0.1
Github though does not offer me to create a PR that would transfer the branch to your repo.
Do you want to add me as collaborator on this repo so I can push the release-1.9.0.1 branch (and then also a new tag) here?

**Comment by simonmichael** [comment]
Invitation sent, thank you very much.

**Comment by andreasabel** [comment]
I pushed the `release-1.9.0.1` branch and a tagged it with `1.9.0.1`.

**Comment by andreasabel** [comment]
I patched CI to pass `--silent` to `stack`, now all tests pass.
